package org.sir.appgestionstock.service.facade.ventes.devis;
import org.sir.appgestionstock.bean.core.ventes.devis.Devis;
import org.sir.appgestionstock.bean.core.parametres.Entreprise;
import org.sir.appgestionstock.bean.core.parametres.NiveauPrix;
import org.sir.appgestionstock.bean.core.ventes.Paiement;
import org.sir.appgestionstock.bean.core.ventes.retourproduit.RetourProduit;
import org.sir.appgestionstock.bean.core.ventes.devis.DevisProduit;
import org.sir.appgestionstock.bean.core.contacts.Client;
import org.sir.appgestionstock.bean.core.parametres.Devises;
import org.sir.appgestionstock.bean.core.parametres.Taxe;
import org.sir.appgestionstock.zutils.pagination.Pagination;
import java.util.List;
public interface DevisService {
List<Devis> getDevis(Long id);
Devis findById(Long id);
List<Devis> findAllOptimized();
List<Devis> findAll();
Pagination<Devis> findPaginated(int page, int size);
Devis create(Devis item);
List<Devis> create(List<Devis> item);
Devis update(Devis item);
List<Devis> update(List<Devis> item);
void deleteById(Long id);
void delete(Devis item);
void delete(List<Devis> items);
void deleteByIdIn(List<Long> ids);
int deleteByPaiementId(Long id);
Devis findByPaiementId(Long id);
int deleteByRetourProduitId(Long id);
Devis findByRetourProduitId(Long id);
int deleteByTaxeId(Long id);
List<Devis> findByTaxeId(Long id);
int deleteByTaxeExpeditionId(Long id);
List<Devis> findByTaxeExpeditionId(Long id);
int deleteByClientId(Long id);
List<Devis> findByClientId(Long id);
int deleteByDevisesId(Long id);
List<Devis> findByDevisesId(Long id);
int deleteByNiveauPrixId(Long id);
List<Devis> findByNiveauPrixId(Long id);
int deleteByEntrepriseId(Long id);
List<Devis> findByEntrepriseId(Long id);
    Long findMaxId();
}