package org.sir.appgestionstock.service.facade.produit;
import org.sir.appgestionstock.bean.core.produit.Produit;
import org.sir.appgestionstock.bean.core.parametres.Entreprise;
import org.sir.appgestionstock.bean.core.inventaire.NiveauStock;
import org.sir.appgestionstock.bean.core.produit.ProduitNiveauPrix;
import org.sir.appgestionstock.bean.core.ventes.facture.FactureProduit;
import org.sir.appgestionstock.bean.core.ventes.devis.DevisProduit;
import org.sir.appgestionstock.bean.core.inventaire.boncommande.BonCommandeProduit;
import org.sir.appgestionstock.bean.core.ventes.retourproduit.RetourProduitProduit;
import org.sir.appgestionstock.bean.core.contacts.Fournisseur;
import org.sir.appgestionstock.bean.core.inventaire.livraison.LivraisonProduit;
import org.sir.appgestionstock.bean.core.parametres.Devises;
import org.sir.appgestionstock.bean.core.ventes.commande.CommandeProduit;
import org.sir.appgestionstock.bean.core.parametres.Taxe;
import org.sir.appgestionstock.zutils.pagination.Pagination;
import java.util.List;
public interface ProduitService {
    double getNbProduits(Long idEntreprise);
    Produit findById(Long id);
    List<Produit> getProduits(Long idEntreprise);
List<Produit> findAllOptimized();
List<Produit> findAll();
Pagination<Produit> findPaginated(int page, int size);
Produit create(Produit item);
List<Produit> create(List<Produit> item);
Produit update(Produit item);
List<Produit> update(List<Produit> item);
void deleteById(Long id);
void delete(Produit item);
void delete(List<Produit> items);
void deleteByIdIn(List<Long> ids);
int deleteByNiveauStockId(Long id);
Produit findByNiveauStockId(Long id);
int deleteByDevisesId(Long id);
List<Produit> findByDevisesId(Long id);
int deleteByTaxeId(Long id);
List<Produit> findByTaxeId(Long id);
int deleteByFournisseurId(Long id);
List<Produit> findByFournisseurId(Long id);
int deleteByEntrepriseId(Long id);
List<Produit> findByEntrepriseId(Long id);
}