package org.sir.appgestionstock.service.facade.ventes.facture;
import org.sir.appgestionstock.bean.core.ventes.commande.Commande;
import org.sir.appgestionstock.bean.core.ventes.facture.Facture;
import org.sir.appgestionstock.bean.core.adresse.Adresse;
import org.sir.appgestionstock.bean.core.parametres.Entreprise;
import org.sir.appgestionstock.bean.core.parametres.NiveauPrix;
import org.sir.appgestionstock.bean.core.ventes.Paiement;
import org.sir.appgestionstock.bean.core.ventes.retourproduit.RetourProduit;
import org.sir.appgestionstock.bean.core.ventes.facture.FactureProduit;
import org.sir.appgestionstock.bean.core.contacts.Client;
import org.sir.appgestionstock.bean.core.parametres.Devises;
import org.sir.appgestionstock.bean.core.parametres.Taxe;
import org.sir.appgestionstock.zutils.pagination.Pagination;
import java.util.List;
public interface FactureService {
Facture findById(Long id);
List<Facture> getFactures(Long entrepriseId);

List<Facture> findAllOptimized();
List<Facture> findAll();
Pagination<Facture> findPaginated(int page, int size);
Facture create(Facture item);
List<Facture> create(List<Facture> item);
Facture update(Facture item);
List<Facture> update(List<Facture> item);
void deleteById(Long id);
void delete(Facture item);
void delete(List<Facture> items);
void deleteByIdIn(List<Long> ids);
int deleteByPaiementId(Long id);
Facture findByPaiementId(Long id);
int deleteByRetourProduitId(Long id);
Facture findByRetourProduitId(Long id);
int deleteByTaxeId(Long id);
List<Facture> findByTaxeId(Long id);
int deleteByTaxeExpeditionId(Long id);
List<Facture> findByTaxeExpeditionId(Long id);
int deleteByClientId(Long id);
List<Facture> findByClientId(Long id);
int deleteByDevisesId(Long id);
List<Facture> findByDevisesId(Long id);
int deleteByNiveauPrixId(Long id);
List<Facture> findByNiveauPrixId(Long id);
int deleteByAddressFacturationId(Long id);
Facture findByAddressFacturationId(Long id);
int deleteByAddressExpeditionId(Long id);
Facture findByAddressExpeditionId(Long id);
void facturePaiement(Long idF,Long idP);
int deleteByEntrepriseId(Long id);
List<Facture> findByEntrepriseId(Long id);
    Long findMaxId();
}