name: Deploy Spring Boot

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Clean up disk space before build
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo docker system prune -a -f
          df -h

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        run: sudo docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: sudo docker build -t laila23/springboot-example .

      - name: Publish image to Docker Hub
        run: sudo docker push laila23/springboot-example:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Clean up disk space before pulling image
        run: |
          sudo docker system prune -a -f
          sudo docker volume prune -f
          sudo docker network prune -f
          df -h

      - name: Check available disk space
        run: df -h

      - name: Pull Image from Docker Hub
        run: sudo docker pull laila23/springboot-example:latest

      - name: Delete old container
        run: sudo docker rm -f springboot-example-container || true

      - name: Run Docker container
        run: sudo docker run -d -p 8080:8080 --name springboot-example-container laila23/springboot-example
