name: Deploy SpringBoot

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t laila23/springboot-example .

      - name: Publish Image to Docker Hub
        run: docker push laila23/springboot-example:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Check Docker Login
        run: docker info

      - name: Pull Image from Docker Hub
        run: |
          docker pull laila23/springboot-example:latest
          docker images

      - name: Delete Old Container
        run: docker rm -f springboot-example-container || true

      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name springboot-example-container laila23/springboot-example
